/**
 * SUDOKU's placement (`src/engine/placement/sudoku.ts`) on the real ladder: the opening, the fixed
 * quantities, the givens and the guess-free promise; and Sweep on it, which only harvests marks.
 */

import { describe, expect, it } from 'vitest';
import { boardConfig, cumulativeExp } from '../src/engine/config.js';
import { Game } from '../src/engine/game.js';
import { clearableWithoutGuessing } from '../src/engine/placement/sudoku.js';
import { boardsOf, ladders, SEEDS, UNGATED_SWEEP } from './helpers.js';

describe('the sudoku placement', () => {
  const sudokuBoards = boardsOf('sudoku');

  it('opens exactly the nine empty cells, and they pay no EXP', () => {
    // The whole reason the digits are 0-8: tier 0 is a digit, so it lands once
    // per row, column and box, and those nine cells are the opening. A 1-9
    // board would have to pre-kill creatures instead, which grants EXP and
    // would hand the player levels before their first click.
    for (const cfg of sudokuBoards) {
      const game = Game.create(cfg, SEEDS[0]!);
      const open = game.grid.flat().filter((c) => c.open);
      expect(open).toHaveLength(9);
      expect(open.every((c) => c.tier === 0)).toBe(true);
      expect(game.ex).toBe(0);
      expect(game.level).toBe(1);
      expect(game.hp).toBe(game.maxHp);
    }
  });

  it('holds C_k identical on every board, because the rule fixes the quantities', () => {
    // No density dial, no distribution archetype, no tier-count dial. This is
    // what forces the givens count to carry the whole ladder.
    const curves = sudokuBoards.map((cfg) => cumulativeExp(cfg.quantity).join(','));
    expect(new Set(curves).size).toBe(1);
    expect(cumulativeExp(sudokuBoards[0]!.quantity)).toEqual([
      9, 27, 63, 135, 279, 567, 1143, 2295,
    ]);
  });

  it('deals exactly the givens the ladder asked for, always truthfully', () => {
    for (const cfg of sudokuBoards) {
      for (const seed of SEEDS) {
        const game = Game.create(cfg, seed);
        const marked = game.grid.flat().filter((c) => c.mark > 0);
        expect(marked).toHaveLength(cfg.givens);
        // A given is a fact, not a claim: mark-assisted Sweep trusts these.
        expect(marked.every((c) => c.mark === c.tier)).toBe(true);
        // Never on empty ground — the opening already reveals every empty cell.
        expect(marked.every((c) => c.tier > 0)).toBe(true);
      }
    }
  });

  it('never ships a board that needs a guess', () => {
    // The point of the type. At 100% density HP cannot be a guess budget — a
    // tier-8 at LV1 costs 56 against an HP pool of 14-20 — so a board with an
    // unresolvable 50/50 in it is not hard, it is broken.
    for (const cfg of sudokuBoards) {
      for (const seed of SEEDS) {
        const game = Game.create(cfg, seed);
        const tiers: number[] = [];
        const givens: number[] = [];
        for (let y = 0; y < 9; y++) {
          for (let x = 0; x < 9; x++) {
            tiers.push(game.grid[y]![x]!.tier);
            if (game.grid[y]![x]!.mark > 0) givens.push(y * 9 + x);
          }
        }
        const grid = Array.from({ length: 9 }, (_, y) => tiers.slice(y * 9, y * 9 + 9));
        expect(
          clearableWithoutGuessing(grid, givens, cfg.exp, cfg.startLevel),
          `${cfg.typeId}#${cfg.board} seed ${seed}`,
        ).toBe(true);
      }
    }
  });
});

describe('sweep on a sudoku board', () => {
  it('never solves the board for the player', () => {
    // The board is generated by rejecting anything the propagator cannot
    // finish, so a Sweep that reasoned with the Sudoku rule would clear every
    // board of this ladder in one click. It must stay strictly weaker than the
    // generator's own solver, which on every other type happens for free.
    for (const cfg of boardsOf('sudoku')) {
      for (const seed of SEEDS) {
        const game = Game.create(cfg, seed);
        for (let i = 0; i < 20 && game.status === 'playing'; i++) game.sweep();
        expect(game.status, `${cfg.typeId}#${cfg.board} seed ${seed}`).toBe('playing');
        const open = game.grid.flat().filter((c) => c.open).length;
        expect(open, 'sweep alone should not carry the board').toBeLessThan(81);
      }
    }
  });

  it('harvests the marks at or below your level, and nothing else', () => {
    // Sweep on this type is "open what I have already identified". The
    // neighbour-sum proof is not weak here, it is empty: hidden sums run to
    // sixty, so it returned zero cells on every board of the ladder.
    const cfg = boardsOf('sudoku')[0]!;
    const game = Game.create(cfg, SEEDS[0]!, UNGATED_SWEEP);

    const cheap = game.grid.flat().filter((c) => !c.open && c.mark > 0 && c.mark <= game.level);
    const dear = game.grid.flat().filter((c) => !c.open && c.mark > game.level);
    expect(cheap.length, 'board 1 should deal some tier-1 clues').toBeGreaterThan(0);
    expect(dear.length).toBeGreaterThan(0);

    const strict = game.safeCells({ useMarks: false });
    expect(strict.every((c) => c.mark > 0 && c.mark <= game.level)).toBe(true);
    expect(strict.some((c) => dear.includes(c))).toBe(false);

    game.sweep({ useMarks: false });
    expect(game.hp).toBe(game.maxHp);
    expect(cheap.every((c) => c.open)).toBe(true);
    expect(dear.every((c) => !c.open)).toBe(true);
  });

  it('acts on a committed mark, never on an open pencil', () => {
    const cfg = boardsOf('sudoku')[0]!;
    const game = Game.create(cfg, SEEDS[0]!, UNGATED_SWEEP);
    const target = game.grid.flat().find((c) => !c.open && !c.given && c.tier === 1)!;

    game.toggleNote(target.x, target.y, 1);
    expect(game.safeCells().some((c) => c === target)).toBe(false);

    game.setMark(target.x, target.y, 1); // commit it
    expect(game.grid[target.y]![target.x]!.notes).toBe(0);
    expect(game.safeCells().some((c) => c === target)).toBe(true);
    // A mark is the player's claim, so the strict proof still will not take it.
    expect(game.safeCells({ useMarks: false }).some((c) => c === target)).toBe(false);
    game.sweep();
    expect(target.open).toBe(true);
    expect(game.hp).toBe(game.maxHp);
  });

  it('leaves every other ladder sweep untouched', () => {
    // The Sudoku channel is gated on the placement. If that gate leaked, a
    // uniform board would start proving things from a rule it does not obey.
    const cfg = boardConfig(ladders, 'normal', 5);
    const a = Game.create(cfg, SEEDS[0]!);
    expect(cfg.placement).toBe('uniform');
    expect(a.safeCells({ useMarks: false }).length).toBe(
      Game.create(cfg, SEEDS[0]!).safeCells({ useMarks: false }).length,
    );
  });

  it('refuses to let the player rub out a clue', () => {
    const game = Game.create(boardsOf('sudoku')[0]!, SEEDS[0]!);
    const clue = game.grid.flat().find((c) => c.given)!;
    const tier = clue.mark;
    expect(game.setMark(clue.x, clue.y, tier)[0]).toMatchObject({ reason: 'given' });
    expect(game.setMark(clue.x, clue.y, 0)[0]).toMatchObject({ reason: 'given' });
    expect(game.toggleNote(clue.x, clue.y, 1)[0]).toMatchObject({ reason: 'given' });
    expect(clue.mark).toBe(tier);
  });
});
