"""Build the design reference page: the generated data injected into the page template.

    python design/build.py    # writes design/reference.html from design/page.template.html

Each token below is a placeholder in the template, replaced by the JSON file in design/data/ it
names, minified. reference.html is generated: edit the template and rebuild, never the page.
"""
import io, json

from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"

# Each placeholder in the template, and the file in design/data/ that replaces it.
TOKENS = {
    "/*__LADDERS__*/": "ladders.json",
    "/*__OPENING__*/": "opening.json",
    "/*__PLACEMENT__*/": "placement.json",
    "/*__PLACEMENT_RULES__*/": "placement-rules.json",
}
# The page's first line, so a reader of reference.html knows not to edit it.
MARKER = "<!-- Generated by design/build.py from page.template.html. Edit the template. -->\n"

tpl = io.open(HERE / "page.template.html", encoding="utf-8").read()

for token, path in TOKENS.items():
    data = json.load(io.open(DATA / path, encoding="utf-8"))
    blob = json.dumps(data, separators=(",", ":"), ensure_ascii=False)
    assert "</script" not in blob and "<!--" not in blob, f"{path} would break out of its tag"
    assert token in tpl, f"{token} missing from template"
    tpl = tpl.replace(token, blob)

assert not any(token.strip("/*") in tpl for token in TOKENS)
# Why this guard exists is not recorded; it has been here since the initial commit (bead031).
assert not any(0x400 < ord(c) < 0x500 for c in tpl), "stray Cyrillic character"

tpl = MARKER + tpl
io.open(HERE / "reference.html", "w", encoding="utf-8", newline="\n").write(tpl)
print("reference.html", len(tpl), "chars")
