"""Build the creature-icon symbol faces from the symbol table.

    python scripts/pip_symbols.py SYMBOLS2 SYMBOLS EMOJI SANS

Reads src/ui/pipsymbols.json, the symbols the custom-icon window offers, and writes
src/ui/pipfont/: one woff2 per source font holding only the symbols taken from it, and
pipfont.css, which declares them all as one family with a unicode-range each, so every symbol
has exactly one face to come from. Each symbol comes from the first source that has it, in the
order given. The sources, all SIL OFL 1.1, from github.com/google/fonts (ofl/):

    SYMBOLS2  notosanssymbols2/NotoSansSymbols2-Regular.ttf
    SYMBOLS   notosanssymbols/NotoSansSymbols[wght].ttf
    EMOJI     notoemoji/NotoEmoji[wght].ttf  (the monochrome one)
    SANS      notosans/NotoSans[wdth,wght].ttf, or any static Noto Sans Regular

Fails, writing nothing, if any symbol is in none of them. Needs fontTools and brotli.
"""

import json
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, 'src', 'ui', 'pipsymbols.json')
OUT = os.path.join(ROOT, 'src', 'ui', 'pipfont')
FAMILY = 'Pip Symbols'
# The output file for each source, in the order the sources are given.
NAMES = ['symbols2', 'symbols', 'emoji', 'sans']
# Where a source is variable, the weight it is pinned at: the regular, matching Symbols 2,
# which is the source of most of the symbols and comes only in the regular.
WEIGHT = 400


def ranges(cps):
    """Consecutive runs, as a CSS unicode-range."""
    runs = []
    for cp in sorted(cps):
        if runs and cp == runs[-1][1] + 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return ', '.join('U+%X' % a if a == b else 'U+%X-%X' % (a, b) for a, b in runs)


def main(sources):
    if len(sources) != len(NAMES):
        sys.exit(__doc__)
    table = json.load(open(TABLE, encoding='utf-8'))
    wanted = {int(s[1], 16) for group in table['sets'] for s in group['symbols']}

    left = set(wanted)
    plan = []
    for name, path in zip(NAMES, sources):
        font = TTFont(path)
        taken = left & set(font.getBestCmap())
        left -= taken
        if taken:
            plan.append((name, font, taken))
    if left:
        sys.exit('In none of the sources: ' + ' '.join('U+%04X' % c for c in sorted(left)))

    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        os.remove(os.path.join(OUT, f))
    faces = []
    for name, font, taken in plan:
        if 'fvar' in font:
            font = instancer.instantiateVariableFont(font, {'wght': WEIGHT})
        options = subset.Options()
        options.flavor = 'woff2'
        options.layout_features = []
        options.name_IDs = ['*']
        options.notdef_outline = False
        sub = subset.Subsetter(options)
        sub.populate(unicodes=taken)
        sub.subset(font)
        subset.save_font(font, os.path.join(OUT, name + '.woff2'), options)
        faces.append(
            "@font-face {\n"
            f"  font-family: '{FAMILY}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {WEIGHT};\n"
            "  font-display: block;\n"
            f"  src: url('./{name}.woff2') format('woff2');\n"
            f"  unicode-range: {ranges(taken)};\n"
            "}\n"
        )
        print(f'{name}.woff2: {len(taken)} symbols')

    head = (
        '/*\n'
        ' * The creature-icon symbols, as one family. Generated by scripts/pip_symbols.py from\n'
        ' * src/ui/pipsymbols.json; do not edit. Each face holds only the symbols taken from its\n'
        ' * source, and its unicode-range names exactly those, so no symbol has two faces.\n'
        ' */\n\n'
    )
    with open(os.path.join(OUT, 'pipfont.css'), 'w', encoding='utf-8', newline='\n') as css:
        css.write(head + '\n'.join(faces))


if __name__ == '__main__':
    main(sys.argv[1:])
