/**
 * Headless sweep over every board of every ladder.
 *
 *   npm run sim            # 20 seeds per board
 *   npm run sim -- 100     # more seeds
 *
 * Reports the opening the player is handed, and whether an omniscient
 * tier-order player clears the board without losing a point of HP.
 */

import { loadLadders } from '../data.js';
import { boardConfig } from '../engine/config.js';
import { Game } from '../engine/game.js';
import { autoplaySearch, autoplayTierOrder } from './autoplay.js';

const seeds = Number(process.argv[2] ?? 20);
const ladders = loadLadders();

function median(values: number[]): number {
  const s = [...values].sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)] ?? 0;
}

let failures = 0;

for (const type of ladders) {
  // The continuation past board 10 is generated by the same code and has to
  // satisfy the same invariants, so it is swept with the rest rather than
  // taken on trust.
  const rows = [...type.boards, ...type.extended];
  console.log(`\n=== ${type.name} === ladder 1-${type.boards.length}` +
    (type.extended.length ? `, scaling 11-${rows[rows.length - 1]!.n}` : ''));
  console.log(
    'bd'.padStart(3) + 'grid'.padStart(9) + 'creat.'.padStart(8) +
    'opening'.padStart(9) + 'worst'.padStart(7) +
    'cleared'.padStart(9) + 'hp lost'.padStart(9) + 'max lv'.padStart(8),
  );

  for (const row of rows) {
    const cfg = boardConfig(ladders, type.id, row.n);
    const openings: number[] = [];
    let cleared = 0;
    let hpLost = 0;
    let maxLevel = 0;

    for (let s = 0; s < seeds; s++) {
      const game = Game.create(cfg, 0x5eed0000 + s);
      openings.push(game.grid.flat().filter((c) => c.open).length);
      const result = type.search ? autoplaySearch(game) : autoplayTierOrder(game);
      if (result.cleared) cleared++;
      hpLost += result.hpLost;
      maxLevel = Math.max(maxLevel, result.finalLevel);
    }

    if (cleared !== seeds || hpLost !== 0) failures++;
    const ok = cleared === seeds && hpLost === 0;
    console.log(
      String(row.n).padStart(3) +
      `${row.w}x${row.h}`.padStart(9) +
      String(row.monsters).padStart(8) +
      String(median(openings)).padStart(9) +
      String(Math.min(...openings)).padStart(7) +
      `${cleared}/${seeds}`.padStart(9) +
      String(hpLost).padStart(9) +
      String(maxLevel).padStart(8) +
      (ok ? '' : '   <-- FAILED'),
    );
  }
}

const total = ladders.reduce((a, t) => a + t.boards.length + t.extended.length, 0);
console.log(
  `\n${total - failures}/${total} boards cleared by every seed at full HP ` +
  `(${seeds} seeds each, ${total * seeds} boards simulated).`,
);
process.exit(failures === 0 ? 0 : 1);
